version: '3'

services:

  pgscomputacion:
    image: postgres:14
    container_name: pgscomputacion
    network_mode: bridge
    ports:
      - "7432:5434"
    environment:
      POSTGRES_USER       : postgres
      POSTGRES_PASSWORD   : postgres
      POSTGRES_DB : taller
    #ENV PGDATA=/var/lib/postgresql/data
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"

  scomputacion:
    build: .
    ports:
      - "8083:80"
    # expose:
    #   - '80'
    volumes:
      - "./src:/var/www/scomputacion"
    links:
      - pgscomputacion
    depends_on:
      - pgscomputacion
    network_mode: bridge